### ISSUE TITLE
Change upper bound for fmt dependency on rocsolver spack package

### ISSUE THREAD

**Issue by aurianer** [ROCmSoftwarePlatform/rocSOLVER#514]
Is the upper bound of the fmt dependency of the rocsolver spack package here for a specific reason or just because the other versions are not tested? https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/rocsolver/package.py#L125
I would need fmt@9 for my spack build-env, and it seems to work good when I remove this upper bound, I didn't test rocsolver exhaustively though.

**Comment by cgmb** [comment]
The constraint on the rocsolver spack packages was added because fmt 9.0 and 9.1 had issues with hip and sycl [1]. There is a fix on the fmt development branch [2]. Spack has backported the fix to fmt 9.0 and 9.1 [3], so I believe that constraint could be removed from the rocsolver Spack package.

If you'd like to open a PR on spack/spack that removes the upper bound, I'll approve it.

[1] https://github.com/fmtlib/fmt/issues/3005
[2] https://github.com/fmtlib/fmt/commit/0b0f7cfbfcebd021c910078003d413354bd843e2
[3] https://github.com/spack/spack/pull/33733

**Comment by cgmb** [comment]
Oh, I forgot that older versions of rocSOLVER do have a legitimate constraint. We added support for `fmt@8.1:` in `rocsolver@5.2`. We might also need to backport [the patch](https://github.com/ROCmSoftwarePlatform/rocSOLVER/commit/2bbfb8976f6e4d667499c77e41a6433850063e88) to entirely eliminate constraints on older versions of rocsolver.
