### ISSUE TITLE
Size of E of SYEV and other LAPACK(like) functions

### ISSUE THREAD

**Issue by Naraenda** [ROCmSoftwarePlatform/rocSOLVER#543]
The documentation currently doesn't mention the size of the E-parameter in these functions.

[I've found that for `rocsolver_syev` it should be `n * 3 - 1`.](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/1a4498cf91c68f147efdf70868f28c4b489b8fc0/clients/include/testing_syev_heev.hpp#L302) Is this correct? [Quite a few other projects use `|A| = n * n`.](https://github.com/flame/libflame/blob/6a53fea493783f2637e3cfc3c097fcda8b5bfff5/src/base/flamec/wrappers/lapack/hip/FLA_Hevd_external_hip.c#L41) However, if it were just the values of the tridiagonal matrix, shouldn't it be `n * 3 - 2`? It would be nice if someone could verify this, and also update the docs 😄

**Comment by tfalders** [comment]
Hi @Naraenda, `n * 3 - 1` is the size of workspace required for LAPACK; [for rocSOLVER, it is n](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/a6e311dc1c046fd9863b2cec4c6030a93a85e288/clients/include/testing_syev_heev.hpp#L401). This is because the values of the tridiagonal matrix are split between D and E. D contains the `n` diagonal values (which converge to eigenvalues), and E contains the `n-1` off-diagonal values (which converge to zero; and only one off-diagonal is needed since the matrix is symmetric). I will open a PR to have this information added to the docs.

As far as I'm aware, the size of E should be mentioned in the docs as indicated by ["Array on the GPU of dimension n"](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/a6e311dc1c046fd9863b2cec4c6030a93a85e288/library/include/rocsolver/rocsolver-functions.h#L15494). Would you be able to provide a link to or screenshot of the documentation where it's missing?

**Comment by Naraenda** [comment]
Thank you for clarifying! It seems I didn't read it properly 😅 Apologies!
